accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.sign_up, name='sign_up'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('change_password/', views.change_password, name='change_password'),
]

instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("accounts.urls")),
    path("", include("post_profile.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post_profile/urls.py
from django.urls import path
from post_profile import views

app_name = 'post_profile'

urlpatterns = [
    # path('profile/details/<id>', views.add_profile_details, name='profile_details'),
    path('profile/<id>/', views.profile, name='profile'),  
    path('profile/edit/<id>/', views.edit_profile_details, name='edit_profile_details'),
    path('upload_photo/', views.upload_photo, name='upload_photo'), 
    path('photo/<int:id>/', views.photo_detail, name='photo_detail'),
    path('photo/edit/<int:id>/', views.edit_photo, name='edit_photo'),
    path('photo/delete/<int:id>/', views.delete_photo, name='delete_photo'),
    path('like_photo/<int:id>/', views.like_photo, name='like_photo'),
    path('comment_photo/<int:id>/', views.comment_photo, name='comment_photo'),
    path('follow/<int:id>/', views.follow, name='follow'),
    path('unfollow/<int:id>/', views.unfollow, name='unfollow'),
    path('error/<str:message>/', views.error_page, name='error_page'),
    path('search/', views.search_users, name='search_users'),
    path('delete_user/', views.delete_user, name='delete_user'),




    
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
# views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from post_profile.models import Follow, Photo



@login_required(login_url='accounts:login')
def index(request):
    followed_users = Follow.objects.filter(followed_by=request.user).values_list('followed_to', flat=True)
    posts = Photo.objects.filter(user__in=followed_users).order_by('-created_at')
    return render(request, 'accounts/index.html', {'posts': posts})


def sign_up(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('accounts:index')) 
        return render(request, "accounts/sign_up.html")
    elif request.method == "POST":
        user = User.objects.create_user(
            username=request.POST.get('username'),
            email=request.POST.get('email'),
            password=request.POST.get('password'),
            first_name=request.POST.get('first_name'),
            last_name=request.POST.get('last_name')
        )

        # Debugging prints
        print("New user created:", user.username)
        print("New user ID:", user.id)

        # Redirect to edit_profile_details with user's id
        return HttpResponseRedirect(reverse('post_profile:edit_profile_details', kwargs={'id': user.id}))


def login_view(request):
    next_url = request.GET.get('next', '')  # Capture the 'next' parameter from the GET request

    if request.method == "GET":
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('accounts:index')) 
        return render(request, "accounts/log_in.html", {'next_url': next_url})  # Pass 'next_url' to the context
    elif request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        next_url = request.POST.get('next', '')  # Make sure to capture the 'next' parameter from the POST request as well

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect(next_url) if next_url else redirect('accounts:index')
        else:
            return render(request, "accounts/log_in.html", {"login_message": "Username/password is incorrect", 'next_url': next_url})  # Pass 'next_url' to the context again in case of failure



def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('accounts:login')) 


@login_required(login_url='accounts:login')
def change_password(request):
    if request.method == 'POST':
        current_password = request.POST.get('current_password')
        new_password = request.POST.get('new_password')
        user = request.user
        
        if user.check_password(current_password):
            user.set_password(new_password)
            user.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('accounts:change_password')
        else:
            messages.error(request, 'Current password is incorrect.')
            return redirect('accounts:change_password')
    return render(request, 'accounts/change_password.html')

accounts/templates/accounts/change_password.html
{% include "post_profile/navbar.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Change Password</title>
</head>
<body>
    <div style="display: flex; justify-content: center; align-items: center; height: 100vh;">
        
    </div>
    
</body>
</html>

<!DOCTYPE html>
<html>
<head>
    <title>Instagram Login</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background: #fafafa;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            padding-top: 30px;
        }

        .navbar {
            position: fixed; /* This will make the navbar stay at the top */
            top: 0;
            left: 0;
            width: 98.5%; /* This ensures the navbar stretches across the full width */
            z-index: 1000; /* This ensures the navbar stays on top of other content */
        }

        .change-password {
            width: 350px;
            background: #fff;
            padding: 20px;
            border: 2px solid #dbdbdb;
            text-align: center;
            border-radius: 8px;

        }

        .instagram-logo {
            margin: 20px 0;
            width: 85%;
        }

        .form-input {
            width: 94%;
            padding: 10px;
            margin: 5px 0;
            background: #fafafa;
            border: 1px solid #dbdbdb;
            border-radius: 3px;
        }

        .login-btn {
            width: 100%;
            padding: 10px;
            margin: 5px 0;
            background: #0095f6;
            border: none;
            border-radius: 3px;
            color: white;
            font-weight: bold;
            cursor: pointer;
        }

        .divider {
            margin: 20px 0;
            position: relative;
        }

        .divider::before,
        .divider::after {
            content: '';
            flex: 1;
            height: 1px;
            background: #dbdbdb;
            position: absolute;
            top: 50%;
        }

        .divider::before {
            left: 0;
        }

        .divider::after {
            right: 0;
        }

        .divider-text {
            padding: 0 10px;
            background: #fff;
            z-index: 1;
            position: relative;
        }

        .alternative-link {
            margin: 20px 0;
        }
    </style>
</head>
<body>

    <div class="change-password">
        <img class="instagram-logo" src="https://png.monster/wp-content/uploads/2021/01/instagram-clip-art-14-70017bcc-370x132.png" alt="Instagram Logo" width="90%">

        <form action="{% url 'accounts:change_password' %}" method="post">
            {% csrf_token %}
            <input class="form-input" type="password" name="current_password" placeholder="Current Password" required>
            <input class="form-input" type="password" name="new_password" placeholder="New Password" required>
            <button value="Login" id="login" class="login-btn">Change Password</button>
            {% if messages %}
                {% for message in messages %}
                    <div style="color:red;">{{ message }}</div>
                {% endfor %}
            {% endif %}
        </form>
        <div class="divider">
            <span class="divider-text">OR</span>
        </div>

        <div class="alternative-link">
            Edit other <a href="{% url "post_profile:edit_profile_details" user.id %}">Profile Details</a>
        </div>

        {% comment %} <a href="#">Forgot password?</a> {% endcomment %}
    </div>

</body>
</html>

accounts/templates/accounts/index.html
{% include "post_profile/navbar.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Feed</title>
    
<style>
    .feed-container {
        max-width: 600px;
        margin: auto;
        padding: 20px;
    }
    
    .feed-title {
        text-align: center;
        margin-bottom: 20px;
    }
    
    .post {
        border: 1px solid #e1e1e1;
        border-radius: 10px;
        margin-bottom: 20px;
        background-color: #fff;
    }
    
    .post-header {
        display: flex;
        justify-content: space-between;
        padding: 10px 15px;
        border-bottom: 1px solid #e1e1e1;
    }
    
    .post-username, .post-date {
        margin: 0;
    }
    
    .post-image {
        width: 100%;
        height: 50%;
    }
    
    .post-caption {
        padding: 15px;
        font-size: 16px;
    }
    </style>
</head>
<body>
    <div class="feed-container">
        <h1 class="feed-title">Latest Posts</h1>
        {% for post in posts %}
        <div class="post">
            <div class="post-header">
                <a href="{% url "post_profile:profile" post.user.id %}"><h2 class="post-username">{{ post.user.username }}</h2></a>
                <span class="post-date">{{ post.created_at }}</span>
            </div>
            <a href="{% url 'post_profile:photo_detail' post.id %}">
                <img src="{{ post.image.url }}" alt="{{ post.caption }}" class="post-image">
            </a>
            <div class="post-caption">
                <p>{{ post.caption }}</p>
            </div>
        </div>
        {% empty %}
        <p>No posts to show.</p>
        {% endfor %}
    </div>

</body>
</html>

accounts/templates/accounts/log_in.html
<!DOCTYPE html>
<html>
<head>
    <title>Instagram Login</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background: #fafafa;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .instagram-login {
            width: 350px;
            background: #fff;
            padding: 20px;
            border: 2px solid #dbdbdb;
            text-align: center;
            border-radius: 8px;

        }

        .instagram-logo {
            margin: 20px 0;
            width: 85%;
        }

        .form-input {
            width: 94%;
            padding: 10px;
            margin: 5px 0;
            background: #fafafa;
            border: 1px solid #dbdbdb;
            border-radius: 3px;
        }

        .login-btn {
            width: 100%;
            padding: 10px;
            margin: 5px 0;
            background: #0095f6;
            border: none;
            border-radius: 3px;
            color: white;
            font-weight: bold;
            cursor: pointer;
        }

        .divider {
            margin: 20px 0;
            position: relative;
        }

        .divider::before,
        .divider::after {
            content: '';
            flex: 1;
            height: 1px;
            background: #dbdbdb;
            position: absolute;
            top: 50%;
        }

        .divider::before {
            left: 0;
        }

        .divider::after {
            right: 0;
        }

        .divider-text {
            padding: 0 10px;
            background: #fff;
            z-index: 1;
            position: relative;
        }

        .alternative-login {
            margin: 20px 0;
        }
    </style>
</head>
<body>

    <div class="instagram-login">
        <img class="instagram-logo" src="https://png.monster/wp-content/uploads/2021/01/instagram-clip-art-14-70017bcc-370x132.png" alt="Instagram Logo" width="90%">

        <form action="{% url 'accounts:login' %}" method="post">
            {% csrf_token %}
            {% if login_message %}<p style="color: red"><strong>{{ login_message }}</strong></p>{% endif %}
            {% comment %} <label for="username">Username: </label> {% endcomment %}
            <input type="text" class="form-input" value="" name="username" placeholder="Enter username">
            {% comment %} <label for="email">Password: </label> {% endcomment %}
            <input type="password" class="form-input" value="" name="password" placeholder="Enter password">
            <!-- <input type="submit" > -->
            <input type="hidden" name="next" value="{{ next_url }}">
            <button value="Login" id="login" class="login-btn">Log in</button>
        </form>
        
        <div class="divider">
            <span class="divider-text">OR</span>
        </div>

        <div class="alternative-login">
            Don't have an account? <a href="{% url "accounts:sign_up" %}">Sign up</a>
        </div>

        {% comment %} <a href="#">Forgot password?</a> {% endcomment %}
    </div>

</body>
</html>

accounts/templates/accounts/sign_up.html
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram Sign up</title>
    <style>
      body {
        font-family: Arial, sans-serif;
        background: #fafafa;
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
      }

      .instagram-signup {
        width: 350px;
        background: #fff;
        padding: 20px;
        border: 2px solid #dbdbdb;
        text-align: center;
        border-radius: 8px;
      }

      .instagram-logo {
        margin: 20px 0;
        width: 85%;

      }

      .form-input {
        width: 94%;
        padding: 10px;
        margin: 5px 0;
        background: #fafafa;
        border: 1px solid #dbdbdb;
        border-radius: 3px;
      }

      .signup-btn {
        width: 100%;
        padding: 10px;
        margin: 5px 0;
        background: #0095f6;
        border: none;
        border-radius: 3px;
        color: white;
        font-weight: bold;
        cursor: pointer;
      }

      .divider {
        margin: 20px 0;
        position: relative;
      }

      .divider::before,
      .divider::after {
        content: "";
        flex: 1;
        height: 1px;
        background: #dbdbdb;
        position: absolute;
        top: 50%;
      }

      .divider::before {
        left: 0;
      }

      .divider::after {
        right: 0;
      }

      .divider-text {
        padding: 0 10px;
        background: #fff;
        z-index: 1;
        position: relative;
      }

      .alternative-login {
        margin: 20px 0;
      }
    </style>
  </head>
  <body>
    <div class="instagram-signup">
      <img
        class="instagram-logo"
        src="https://png.monster/wp-content/uploads/2021/01/instagram-clip-art-14-70017bcc-370x132.png"
        alt="Instagram Logo"
        width="90%"
      />
      <form action="{% url 'accounts:sign_up' %}" method="post">
        {% csrf_token %} {% if register_message %}
        <p style="color: red"><strong>{{ register_message }}</strong></p>
        {% endif %}
        <input
          type="text"
          class="form-input"
          placeholder="First Name"
          value=""
          name="first_name"
          required
        />
        <input
          type="text"
          class="form-input"
          placeholder="Last Name"
          value=""
          name="last_name"
          required
        />
        <input
          type="email"
          class="form-input"
          placeholder="Email"
          value=""
          name="email"
          required
        />
        <input
          type="text"
          class="form-input"
          placeholder="Username"
          value=""
          name="username"
          required
        />
        <input
          type="password"
          class="form-input"
          placeholder="Password"
          value=""
          name="password"
          required
        />
        <button type="submit" value="Register" id="register" class="signup-btn">
          Sign up
        </button>
      </form>

      <div class="divider">
        <span class="divider-text">OR</span>
      </div>

      <div class="alternative-login">Already have account?
        <a href="{% url "accounts:login" %}">Login</a>
      </div>

      {% comment %} <a href="#">Forgot password?</a> {% endcomment %}
    </div>
  </body>
</html>